### ISSUE TITLE
VS Code got called when Chapter 1:: Bash_Script.sh is exec in CLI

### ISSUE THREAD

**Issue by techtoys** [sborsay/AWS-Serverless-IoT-Book#1]
Hi

I am following Chapter 1 to run the Bash_Script.sh but there is no MQTT message pushing to AWS. Instead, VS Code got call up on my computer with CLI messages as follows:

```
C:\Users\User>Bash_Script.sh

C:\Users\User>
[main 2023-10-20T16:32:41.492Z] update#setState idle
[main 2023-10-20T16:32:42.953Z] WSL is not installed, so could not detect WSL profiles
[main 2023-10-20T16:33:11.495Z] update#setState checking for updates
[main 2023-10-20T16:33:11.597Z] update#setState idle
```

What may go wrong with my setup?

John

**Comment by sborsay** [comment]
I'm running the bash script from the command prompt with Git for Windows.
Git for Windows provides a BASH emulation used to run Git from the command
line.  The problem is likely that Visual code does not have a standard Bash
shell interpreter.  I advise you to use the bash shell tool from  MInGW-64,
cygwin-64, or Git.  The easiest Bash interpreter for windows can be found
here:

https://gitforwindows.org/

SDB

**Comment by sborsay** [comment]
Also I am assume you already installed the AWS CLI?

**Comment by techtoys** [comment]
Hi Stephen

It works once Git got installed on my Windows host:
Just need to run `$ bash iot_Tester.sh`.

Yes, AWS CLI installed.

Thanks.

John

**Comment by sborsay** [comment]
Cool, this may allow it to work from VS Code if you want.  Not sureInstalling the AWS Toolkit for Visual Studio Code - AWS Toolkit for VS Codeaws.amazon.comSent from my iPhoneOn Oct 20, 2023, at 8:32 PM, John Leung ***@***.***> wrote:﻿
Hi Stephen
It works once Git got installed on my Windows host:
Just need to run $ bash iot_Tester.sh.
Thanks.
John
